### ISSUE TITLE
Planning the `Project 4: My Simple Todo`

### ISSUE THREAD

**Issue by AmirhosseinOlyaei** [AmirhosseinOlyaei/my-simple-todo#11]
- Project 4: My Simple Todo  
	- **Front-end work for Project 4: My Simple ToDo**  
		- **Description**  
			- Completing tasks utilizing HTML, CSS and JavaScript to make sure ToDo app works smoothly and as designed.  
		- **Goals**  
			- [x] The app allows your user to add a list of things they want to do  
			- [x] The app allows them to delete the items from the todo list  
		- **Tasks** [Project 4: My Simple ToDo]  
			- [x] Bootstrapping TailwindCSS and GitHub  
			- [ ] Design ToDo app user interface in HTML and TailwindCSS  
				- *HTML*  
					- create a form to get info from users  
						- [ ] an input:textnew-list  
			- [ ] Implement functionality in JS with DOM, Array, callbacks, Object literals, and Loops  
				- [ ] when user adds a new list, they see the list in the app:  
					- List 1  
					- List 2  
				- [ ] user can remove a list from the lists  
				- [ ] when user adds an item to each list, item shows on that list  
					- List 1  
						- ~~Item 1~~  
						- Item 2  
				- [ ] when user removes an item from each list, that list shows the rest of the items.  
				- [ ] user can assign a person to each item in the list  
				- [ ] if user checks an item, cross a line on the item name.  
					- List 2  
						- Item 1  
						- Item 2  
			- [x] Integrate with back-end  
				- Deploy to Vercel
